"""
demos.py — 15 projets de démonstration en génie logiciel.
"""

PROJETS_DEMO = [
    # ── 1 ──
    dict(
        libelle="Système de Gestion de Bibliothèque",
        type_projet="Académique",
        date_duree="Octobre 2025 – Décembre 2025",
        contexte="Projet de fin de module Bases de Données, L2 Informatique. Développement d'un système complet de gestion pour une bibliothèque universitaire.",
        problematique="La bibliothèque de l'université gère manuellement les emprunts, retours et catalogues de livres, ce qui entraîne des erreurs, des pertes et un suivi inefficace.",
        objectif="Développer une application web permettant de gérer le catalogue de livres, les emprunts, les retours et les adhérents avec un système d'alertes pour les retards.",
        description_detail="Application CRUD complète avec gestion des utilisateurs (bibliothécaire et adhérent), catalogue de livres avec recherche avancée, système d'emprunts avec dates limites et pénalités de retard.",
        source_donnees="Base de données PostgreSQL créée à partir du catalogue existant",
        type_donnees="Relationnelle (tables : livres, adhérents, emprunts, catégories)",
        taille_dataset="5 000 livres, 800 adhérents, 15 000 emprunts historiques",
        pretraitements="Normalisation des données existantes, suppression des doublons, création des relations entre tables",
        approche="Développement web full-stack avec architecture MVC",
        etapes="1. Analyse des besoins et modélisation UML\n2. Conception de la base de données (MCD/MLD)\n3. Développement du backend Flask\n4. Création de l'interface utilisateur\n5. Tests unitaires et d'intégration\n6. Déploiement",
        algorithmes="Recherche full-text PostgreSQL, algorithme de calcul de pénalités",
        langages="Python, HTML, CSS, JavaScript, SQL",
        librairies="Flask-SQLAlchemy, Flask-Login, Flask-WTF, Jinja2, Bootstrap",
        outils="VS Code, Git, GitHub, pgAdmin, Postman",
        frameworks="Flask",
        performances="Temps de réponse < 200ms, support de 100 utilisateurs simultanés",
        visualisations="Dashboard des emprunts en cours, graphique des livres les plus empruntés, rapport mensuel d'activité",
        resultats_concrets="Réduction de 70% du temps de traitement des emprunts, suppression des pertes de livres non tracées, système d'alertes automatiques par email.",
        competences="Modélisation de bases de données, Développement web MVC, SQL avancé, Gestion de sessions, Tests unitaires",
        difficultes="Gestion des transactions concurrentes (deux personnes empruntant le même livre), migration des données existantes, gestion des rôles utilisateurs.",
        solutions="Utilisation de verrous optimistes en base, script de migration avec validation, système de rôles basé sur Flask-Login avec décorateurs.",
        perspectives="Ajout d'un système de recommandation basé sur l'historique d'emprunts, intégration d'un scanner de code-barres, application mobile.",
        lien_github="https://github.com/exemple/biblio-gestion",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 2 ──
    dict(
        libelle="Plateforme E-commerce avec Panier",
        type_projet="Personnel",
        date_duree="Novembre 2025 – Février 2026",
        contexte="Projet personnel pour maîtriser le développement web full-stack et les systèmes de paiement en ligne.",
        problematique="Les petits commerçants sénégalais n'ont pas accès à des plateformes e-commerce abordables et adaptées au marché local (paiement mobile, livraison locale).",
        objectif="Créer une plateforme e-commerce complète avec gestion de produits, panier, commandes et intégration de paiement mobile.",
        description_detail="Marketplace multi-vendeurs avec catalogue produits, panier persistant, tunnel d'achat, gestion des commandes et tableau de bord vendeur.",
        source_donnees="Base de données MySQL",
        type_donnees="Relationnelle (produits, commandes, utilisateurs, paiements)",
        taille_dataset="2 000 produits, 500 utilisateurs test",
        pretraitements="Optimisation des images produits, indexation des recherches",
        approche="Architecture REST API + Frontend séparé",
        etapes="1. Wireframes et maquettes UI/UX\n2. Modélisation de la base de données\n3. API REST (CRUD produits, commandes)\n4. Frontend responsive\n5. Intégration paiement\n6. Tests end-to-end",
        algorithmes="Recherche par pertinence, calcul automatique des frais de livraison par zone",
        langages="Python, JavaScript, HTML, CSS, SQL",
        librairies="Flask-RESTful, SQLAlchemy, Marshmallow, jQuery, Bootstrap 5",
        outils="VS Code, Git, MySQL Workbench, Figma, Postman",
        frameworks="Flask, Bootstrap",
        performances="API : temps de réponse moyen 150ms, support du pagination côté serveur",
        visualisations="Dashboard vendeur avec graphiques de ventes, historique commandes, statistiques produits",
        resultats_concrets="Plateforme fonctionnelle avec 50 produits en test, tunnel d'achat complet, notifications email automatiques.",
        competences="API REST, Architecture client-serveur, Base de données relationnelle, UI/UX Design, Intégration de paiement",
        difficultes="Gestion du panier en session vs base de données, sécurisation des paiements, performance des requêtes avec jointures multiples.",
        solutions="Panier hybride (session + DB pour utilisateurs connectés), HTTPS + tokens CSRF, optimisation des requêtes avec eager loading.",
        perspectives="Application mobile React Native, système de notation et avis, intégration Wave/Orange Money, recommandation produits par ML.",
        lien_github="https://github.com/exemple/ecommerce-sn",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 3 ──
    dict(
        libelle="Système de Suivi de Bugs (Bug Tracker)",
        type_projet="Académique",
        date_duree="Janvier 2026 – Mars 2026",
        contexte="Projet de module Génie Logiciel, L2 IR. Développement d'un outil de suivi de bugs inspiré de Jira/GitHub Issues.",
        problematique="Les équipes de développement ont besoin d'un outil centralisé pour signaler, suivre et résoudre les bugs de manière organisée et traçable.",
        objectif="Développer un système de tickets permettant de créer, assigner, prioriser et suivre les bugs avec un workflow de résolution.",
        description_detail="Application web avec système de tickets (création, assignation, changement de statut), filtres avancés, commentaires, pièces jointes et notifications.",
        source_donnees="Base de données SQLite",
        type_donnees="Relationnelle (tickets, utilisateurs, commentaires, projets)",
        taille_dataset="Données générées pour tests : 200 tickets, 10 projets",
        pretraitements="Validation des entrées, sanitization HTML pour les descriptions",
        approche="Développement Agile avec sprints de 2 semaines",
        etapes="1. User stories et backlog\n2. Modélisation UML (diagrammes de classes et de séquence)\n3. Sprint 1 : CRUD tickets et authentification\n4. Sprint 2 : workflow de statuts et filtres\n5. Sprint 3 : commentaires et notifications\n6. Tests et documentation",
        algorithmes="Machine à états pour le workflow des tickets (Nouveau → En cours → Résolu → Fermé)",
        langages="Python, HTML, CSS, JavaScript",
        librairies="Flask, SQLAlchemy, Flask-Login, Flask-Mail, WTForms",
        outils="VS Code, Git, GitHub, SQLite Browser, draw.io",
        frameworks="Flask",
        performances="Temps de chargement < 300ms, pagination des listes de tickets",
        visualisations="Tableau Kanban des tickets par statut, graphiques de bugs par priorité et par projet",
        resultats_concrets="Système fonctionnel avec 5 statuts de workflow, système de notifications par email, export CSV des tickets.",
        competences="Conception UML, Design patterns (State, Observer), Développement Agile, Gestion de workflow, Tests automatisés",
        difficultes="Gestion des transitions de statut autorisées, notifications en temps réel, gestion des permissions par rôle.",
        solutions="Pattern State pour les transitions, polling AJAX pour les notifications, système de rôles (admin, développeur, testeur).",
        perspectives="Notifications temps réel avec WebSocket, intégration Git (lier commits aux tickets), API REST pour intégration CI/CD.",
        lien_github="https://github.com/exemple/bug-tracker",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 4 ──
    dict(
        libelle="API REST de Gestion d'Inventaire",
        type_projet="Professionnel",
        date_duree="Décembre 2025 – Février 2026",
        contexte="Stage en entreprise dans une PME de distribution. Besoin d'une API pour connecter le stock physique au site web.",
        problematique="Le stock n'est pas synchronisé entre le magasin physique et le site web, causant des surventes et des clients mécontents.",
        objectif="Concevoir une API REST robuste permettant la gestion en temps réel de l'inventaire avec synchronisation multi-canaux.",
        description_detail="API RESTful documentée avec Swagger, gestion des produits, entrées/sorties de stock, alertes de seuil minimum et historique des mouvements.",
        source_donnees="Base de données PostgreSQL existante de l'entreprise",
        type_donnees="Relationnelle (produits, mouvements, fournisseurs, catégories)",
        taille_dataset="8 000 produits, 50 000 mouvements mensuels",
        pretraitements="Migration et nettoyage de la base existante, normalisation des codes produits",
        approche="API-first design avec documentation OpenAPI/Swagger",
        etapes="1. Spécification OpenAPI\n2. Modélisation base de données\n3. Développement des endpoints CRUD\n4. Authentification JWT\n5. Tests automatisés (pytest)\n6. Documentation et déploiement",
        algorithmes="Calcul de point de commande, algorithme de suggestion de réapprovisionnement basé sur la rotation des stocks",
        langages="Python, SQL",
        librairies="Flask-RESTful, SQLAlchemy, Marshmallow, Flask-JWT-Extended, pytest, Flasgger",
        outils="VS Code, Postman, Git, Docker, pgAdmin",
        frameworks="Flask",
        performances="< 100ms par requête, support de 500 requêtes/minute, pagination et filtres optimisés",
        visualisations="Documentation Swagger interactive, dashboard de suivi des stocks",
        resultats_concrets="Synchronisation en temps réel réduisant les surventes de 95%, temps de vérification de stock passé de 15min à 2sec.",
        competences="Conception d'API REST, Authentification JWT, Documentation OpenAPI, Tests automatisés, Docker, Gestion de base de données",
        difficultes="Gestion des transactions concurrentes sur le stock, performance avec des volumes importants, rétro-compatibilité avec le système existant.",
        solutions="Transactions ACID avec verrouillage pessimiste, indexation stratégique, versioning de l'API (v1, v2).",
        perspectives="Microservices pour séparer stock/commandes/fournisseurs, intégration ERP, prédiction de demande par ML.",
        lien_github="https://github.com/exemple/inventory-api",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 5 ──
    dict(
        libelle="Application de Chat en Temps Réel",
        type_projet="Personnel",
        date_duree="Février 2026 – Mars 2026",
        contexte="Projet personnel pour apprendre les WebSockets et la communication en temps réel.",
        problematique="Les applications de messagerie instantanée nécessitent une communication bidirectionnelle en temps réel, ce qui dépasse le modèle classique requête/réponse HTTP.",
        objectif="Développer une application de chat multi-salons avec messages en temps réel, indicateur de frappe et notifications.",
        description_detail="Application de messagerie avec salons publics et privés, envoi de messages instantanés via WebSocket, historique persistant et indicateurs de présence.",
        source_donnees="Base de données MongoDB",
        type_donnees="Document (messages, utilisateurs, salons)",
        taille_dataset="Données temps réel, historique de 10 000 messages en test",
        pretraitements="Sanitization des messages (protection XSS), compression des données WebSocket",
        approche="Architecture événementielle avec WebSockets",
        etapes="1. Setup serveur WebSocket\n2. Interface de chat responsive\n3. Gestion des salons\n4. Persistance des messages\n5. Indicateurs temps réel\n6. Déploiement",
        algorithmes="Pub/Sub pour la diffusion des messages, algorithme de reconnexion automatique",
        langages="Python, JavaScript, HTML, CSS",
        librairies="Flask-SocketIO, Socket.IO (client), MongoDB PyMongo",
        outils="VS Code, Git, MongoDB Compass, Chrome DevTools",
        frameworks="Flask, Socket.IO",
        performances="Latence < 50ms, support de 200 connexions simultanées en test",
        visualisations="Interface de chat avec bulles de messages, liste des utilisateurs en ligne, indicateurs de frappe",
        resultats_concrets="Application fonctionnelle avec 5 salons, messages instantanés, persistance complète de l'historique.",
        competences="WebSockets, Communication temps réel, NoSQL (MongoDB), Architecture événementielle, JavaScript asynchrone",
        difficultes="Gestion des déconnexions réseau, scalabilité des connexions WebSocket, synchronisation de l'état entre clients.",
        solutions="Heartbeat et reconnexion automatique, architecture pub/sub, versioning des messages pour la synchronisation.",
        perspectives="Ajout du chiffrement end-to-end, partage de fichiers, appels audio/vidéo avec WebRTC.",
        lien_github="https://github.com/exemple/realtime-chat",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 6 ──
    dict(
        libelle="Pipeline CI/CD avec Tests Automatisés",
        type_projet="Académique",
        date_duree="Mars 2026 – Avril 2026",
        contexte="Projet de module DevOps, L2 IR. Mise en place d'un pipeline d'intégration et déploiement continus.",
        problematique="Le déploiement manuel est source d'erreurs et de temps perdu. Comment automatiser les tests et le déploiement à chaque modification du code ?",
        objectif="Mettre en place un pipeline CI/CD complet automatisant les tests, l'analyse de code et le déploiement.",
        description_detail="Pipeline GitHub Actions avec lint, tests unitaires, tests d'intégration, analyse de couverture, build Docker et déploiement automatique.",
        source_donnees="Repository GitHub du projet",
        type_donnees="Code source Python et fichiers de configuration YAML",
        taille_dataset="N/A",
        pretraitements="Configuration des environnements de test, création des fixtures",
        approche="DevOps — Intégration Continue / Déploiement Continu",
        etapes="1. Écriture des tests unitaires (pytest)\n2. Configuration GitHub Actions\n3. Ajout du linting (flake8, black)\n4. Analyse de couverture (coverage.py)\n5. Build Docker automatique\n6. Déploiement sur serveur de staging",
        algorithmes="",
        langages="Python, YAML, Bash, Dockerfile",
        librairies="pytest, pytest-cov, flake8, black, coverage",
        outils="GitHub Actions, Docker, Git, VS Code",
        frameworks="",
        performances="Pipeline complet en < 3 minutes, couverture de tests > 85%",
        visualisations="Badge de statut CI, rapport de couverture sur Codecov, logs de pipeline",
        resultats_concrets="Temps de déploiement réduit de 30min à 3min, détection de 12 bugs avant production grâce aux tests automatisés.",
        competences="CI/CD, Docker, Tests automatisés, GitHub Actions, DevOps, Qualité de code",
        difficultes="Gestion des secrets dans le pipeline, tests d'intégration avec base de données, cache des dépendances.",
        solutions="GitHub Secrets pour les variables sensibles, services Docker dans le pipeline pour la DB, cache pip avec actions/cache.",
        perspectives="Ajout de tests de performance, déploiement blue/green, monitoring post-déploiement, Kubernetes.",
        lien_github="https://github.com/exemple/ci-cd-pipeline",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 7 ──
    dict(
        libelle="Gestionnaire de Projets Agile (Kanban)",
        type_projet="Académique",
        date_duree="Février 2026 – Avril 2026",
        contexte="Projet de module Gestion de Projet, L2 IR. Création d'un outil de gestion de tâches inspiré de Trello.",
        problematique="Les équipes étudiantes manquent d'outils simples et gratuits pour organiser leurs projets en mode Agile.",
        objectif="Développer une application web Kanban permettant de gérer des projets avec des tableaux, des colonnes et des cartes déplaçables.",
        description_detail="Application Kanban avec drag-and-drop, gestion de projets multiples, assignation de tâches, labels de priorité et deadlines.",
        source_donnees="SQLite",
        type_donnees="Relationnelle (projets, colonnes, cartes, utilisateurs)",
        taille_dataset="Données test : 5 projets, 50 cartes",
        pretraitements="",
        approche="Développement web interactif avec JavaScript",
        etapes="1. Maquettage de l'interface Kanban\n2. Backend API REST\n3. Frontend avec drag-and-drop\n4. Système d'assignation\n5. Notifications de deadline\n6. Tests",
        algorithmes="Algorithme de réordonnancement des cartes (position indexée), tri par priorité et deadline",
        langages="Python, JavaScript, HTML, CSS",
        librairies="Flask, SQLAlchemy, SortableJS, Fetch API",
        outils="VS Code, Git, Figma",
        frameworks="Flask",
        performances="Drag-and-drop fluide, mise à jour instantanée via AJAX",
        visualisations="Tableau Kanban interactif, graphique burndown, statistiques par projet",
        resultats_concrets="Outil utilisé par 3 groupes de TD pour organiser leurs projets de semestre.",
        competences="Développement web interactif, API REST, JavaScript DOM, Drag-and-drop, Méthodologie Agile",
        difficultes="Synchronisation du drag-and-drop avec le backend, gestion de l'ordre des cartes, responsive sur mobile.",
        solutions="Requêtes AJAX optimistes (mise à jour UI immédiate, sync serveur en arrière-plan), indexation float pour l'ordre.",
        perspectives="Collaboration temps réel avec WebSocket, application mobile, intégration calendrier.",
        lien_github="https://github.com/exemple/kanban-agile",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 8 ──
    dict(
        libelle="Application de Suivi de Dépenses",
        type_projet="Personnel",
        date_duree="Décembre 2025 – Janvier 2026",
        contexte="Projet personnel pour gérer son budget étudiant et apprendre le développement mobile.",
        problematique="Les étudiants ont du mal à suivre leurs dépenses quotidiennes et à respecter un budget mensuel.",
        objectif="Développer une application permettant de saisir, catégoriser et visualiser ses dépenses avec des objectifs budgétaires.",
        description_detail="Application avec saisie rapide de dépenses, catégorisation automatique, graphiques de répartition et alertes de dépassement de budget.",
        source_donnees="Saisie utilisateur, stockage local SQLite",
        type_donnees="Tabulaire (dépenses, catégories, budgets)",
        taille_dataset="Données personnelles : ~200 transactions/mois",
        pretraitements="Catégorisation automatique basée sur des mots-clés",
        approche="Application mobile cross-platform",
        etapes="1. Design UI/UX mobile-first\n2. Base de données locale\n3. Saisie et catégorisation\n4. Graphiques et statistiques\n5. Système de budgets et alertes\n6. Export des données",
        algorithmes="Catégorisation par mots-clés, calcul de moyennes glissantes pour les prévisions",
        langages="Python",
        librairies="Streamlit, Pandas, Plotly, SQLite3",
        outils="VS Code, Git",
        frameworks="Streamlit",
        performances="Interface réactive, chargement des graphiques < 1s",
        visualisations="Camembert des dépenses par catégorie, courbe d'évolution mensuelle, barres de progression budgétaire",
        resultats_concrets="Économie de 15% sur le budget mensuel grâce à la visibilité sur les dépenses superflues.",
        competences="Développement d'application, Visualisation de données, UX mobile, Gestion de données locales",
        difficultes="UX de saisie rapide (minimiser les clics), synchronisation entre appareils, catégorisation précise.",
        solutions="Interface simplifiée avec suggestions, export/import JSON pour la synchro, dictionnaire de mots-clés extensible.",
        perspectives="Synchronisation cloud, OCR sur les tickets de caisse, prédiction de dépenses par ML, version mobile native.",
        lien_github="https://github.com/exemple/expense-tracker",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 9 ──
    dict(
        libelle="Système d'Authentification Sécurisé",
        type_projet="Académique",
        date_duree="Novembre 2025 – Décembre 2025",
        contexte="Projet de module Sécurité Informatique, L2 IR. Étude et implémentation des mécanismes d'authentification modernes.",
        problematique="Les failles d'authentification (mots de passe faibles, stockage en clair, absence de 2FA) sont la première cause de piratage de comptes.",
        objectif="Implémenter un système d'authentification sécurisé avec hachage bcrypt, JWT, 2FA et protection contre les attaques courantes.",
        description_detail="Module d'authentification avec inscription, connexion, réinitialisation de mot de passe, authentification à deux facteurs (TOTP) et protection CSRF/brute-force.",
        source_donnees="Base de données PostgreSQL",
        type_donnees="Utilisateurs, sessions, tokens, logs de connexion",
        taille_dataset="500 utilisateurs test",
        pretraitements="Validation et sanitization des entrées utilisateur",
        approche="Sécurité en profondeur (defense in depth)",
        etapes="1. Étude des vulnérabilités OWASP\n2. Hachage bcrypt avec salt\n3. Tokens JWT avec expiration\n4. 2FA avec TOTP (Google Authenticator)\n5. Rate limiting anti-brute-force\n6. Tests de sécurité",
        algorithmes="bcrypt (hachage adaptatif), TOTP (RFC 6238), HMAC-SHA256 (JWT)",
        langages="Python, SQL",
        librairies="Flask-Bcrypt, PyJWT, pyotp, Flask-Limiter, Flask-WTF",
        outils="VS Code, Git, Burp Suite (tests), OWASP ZAP",
        frameworks="Flask",
        performances="Hachage bcrypt en ~200ms (sécurité intentionnelle), vérification JWT < 5ms",
        visualisations="Logs de connexion, tableau des tentatives échouées, historique des sessions actives",
        resultats_concrets="Résistance aux attaques par dictionnaire (bcrypt), brute-force (rate limiting 5 tentatives/min), et vol de session (JWT avec expiration courte).",
        competences="Sécurité web, Cryptographie appliquée, Authentification, Protection OWASP Top 10, Tests de pénétration",
        difficultes="Équilibre entre sécurité et UX (trop de vérifications frustre l'utilisateur), gestion du 2FA en cas de perte de téléphone.",
        solutions="2FA optionnel avec codes de récupération, rate limiting progressif, messages d'erreur génériques (ne pas révéler si le compte existe).",
        perspectives="Authentification biométrique, SSO avec OAuth2, analyse comportementale pour détecter les connexions suspectes.",
        lien_github="https://github.com/exemple/secure-auth",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 10 ──
    dict(
        libelle="Plateforme de Réservation de Salles",
        type_projet="Professionnel",
        date_duree="Janvier 2026 – Mars 2026",
        contexte="Développement pour l'administration de l'université afin de gérer les réservations de salles de cours et de réunion.",
        problematique="Les conflits de réservation de salles sont fréquents car le planning est géré sur un tableau Excel partagé, sans vérification de disponibilité en temps réel.",
        objectif="Créer une plateforme web de réservation avec calendrier visuel, vérification de disponibilité et validation par l'administration.",
        description_detail="Application avec calendrier interactif, recherche de salles par capacité et équipement, système de réservation avec validation, et notifications automatiques.",
        source_donnees="Base de données SQLite",
        type_donnees="Relationnelle (salles, réservations, utilisateurs, équipements)",
        taille_dataset="30 salles, 500 réservations/semaine",
        pretraitements="Import du fichier Excel existant, normalisation des créneaux horaires",
        approche="Développement web avec calendrier interactif",
        etapes="1. Analyse des besoins avec l'administration\n2. Modélisation de la base\n3. API de gestion des réservations\n4. Interface calendrier avec FullCalendar.js\n5. Système de validation\n6. Déploiement intranet",
        algorithmes="Détection de conflits horaires (chevauchement d'intervalles), recherche de créneaux libres",
        langages="Python, JavaScript, HTML, CSS, SQL",
        librairies="Flask, SQLAlchemy, FullCalendar.js, Moment.js",
        outils="VS Code, Git, SQLite Browser",
        frameworks="Flask",
        performances="Vérification de disponibilité en < 50ms, affichage calendrier fluide",
        visualisations="Calendrier interactif par salle et par semaine, taux d'occupation par salle, heatmap des créneaux",
        resultats_concrets="Élimination de 100% des conflits de réservation, gain de temps de 80% pour l'administration.",
        competences="Développement web, Gestion de calendrier, Algorithmes d'intervalles, Déploiement intranet, Analyse des besoins",
        difficultes="Gestion des réservations récurrentes (chaque mardi de 8h à 10h), fuseaux horaires, annulations en cascade.",
        solutions="Système de récurrence avec exceptions, stockage en UTC avec conversion côté client, soft delete avec historique.",
        perspectives="Application mobile pour les professeurs, intégration avec Google Calendar, système de check-in par QR code.",
        lien_github="https://github.com/exemple/booking-rooms",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 11 ──
    dict(
        libelle="Outil de Monitoring d'Applications Web",
        type_projet="Personnel",
        date_duree="Mars 2026 – Avril 2026",
        contexte="Projet personnel pour surveiller la disponibilité et les performances de sites web.",
        problematique="Les développeurs ne sont pas alertés quand leurs applications tombent en panne ou deviennent lentes, ce qui impacte les utilisateurs.",
        objectif="Développer un outil de monitoring qui vérifie périodiquement la disponibilité et le temps de réponse d'URLs configurées, avec alertes.",
        description_detail="Application de monitoring avec vérification périodique (ping HTTP), historique des temps de réponse, alertes par email en cas de panne, et dashboard de statut.",
        source_donnees="Données collectées en temps réel (requêtes HTTP vers les URLs surveillées)",
        type_donnees="Séries temporelles (timestamp, URL, status_code, response_time)",
        taille_dataset="~10 000 mesures/jour pour 20 URLs",
        pretraitements="Agrégation par heure/jour, calcul de moyennes mobiles, détection d'anomalies",
        approche="Application de collecte de métriques avec scheduling",
        etapes="1. Module de vérification HTTP\n2. Scheduler (APScheduler)\n3. Stockage des métriques\n4. Système d'alertes email\n5. Dashboard de visualisation\n6. Configuration des URLs",
        algorithmes="Détection d'anomalies par seuil et écart-type, moyenne mobile exponentielle",
        langages="Python",
        librairies="Requests, APScheduler, Streamlit, Plotly, smtplib",
        outils="VS Code, Git",
        frameworks="Streamlit",
        performances="Vérification de 20 URLs en < 10s, dashboard temps réel",
        visualisations="Timeline de disponibilité (uptime), graphique de temps de réponse, statut en temps réel avec code couleur",
        resultats_concrets="Détection de 3 pannes sur des projets personnels avant que les utilisateurs ne les remarquent.",
        competences="HTTP et protocoles web, Scheduling, Séries temporelles, Alerting, Dashboard en temps réel",
        difficultes="Faux positifs (timeout réseau vs vraie panne), gestion des threads pour les vérifications parallèles, stockage efficace des métriques.",
        solutions="Vérification en double avant alerte, ThreadPoolExecutor pour les requêtes parallèles, rotation des données anciennes.",
        perspectives="Monitoring de métriques applicatives (CPU, RAM), intégration Slack/Telegram, page de statut publique.",
        lien_github="https://github.com/exemple/web-monitor",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 12 ──
    dict(
        libelle="CMS Minimaliste (Blog Engine)",
        type_projet="Académique",
        date_duree="Octobre 2025 – Novembre 2025",
        contexte="Projet de module Développement Web, L2 IR. Création d'un système de gestion de contenu simplifié.",
        problematique="WordPress est trop complexe pour un blog simple. Comment créer un CMS léger, rapide et facile à personnaliser ?",
        objectif="Développer un CMS minimaliste permettant de créer, éditer et publier des articles avec un rendu Markdown.",
        description_detail="Blog engine avec éditeur Markdown, gestion de catégories et tags, système de brouillons et publications, thèmes personnalisables et flux RSS.",
        source_donnees="Fichiers Markdown et base SQLite",
        type_donnees="Texte Markdown + métadonnées en base",
        taille_dataset="50 articles de test",
        pretraitements="Conversion Markdown → HTML, extraction des métadonnées (titre, date, tags)",
        approche="Architecture simple avec rendu côté serveur",
        etapes="1. Système de fichiers Markdown\n2. Rendu HTML avec templates\n3. Panel d'administration\n4. Catégories et tags\n5. Flux RSS\n6. Déploiement",
        algorithmes="Parser Markdown, génération de slugs URL-friendly, pagination",
        langages="Python, HTML, CSS, Markdown",
        librairies="Flask, Markdown2, Jinja2, FeedGenerator",
        outils="VS Code, Git",
        frameworks="Flask",
        performances="Génération de page < 50ms, cache des articles convertis",
        visualisations="Blog responsive avec thème clair, archive par mois, nuage de tags",
        resultats_concrets="CMS fonctionnel déployé sur PythonAnywhere, utilisé comme blog personnel.",
        competences="Développement web, Parsing Markdown, Architecture CMS, Templating, SEO basique",
        difficultes="Gestion du cache lors de la modification d'articles, SEO (URLs propres, métadonnées), sécurité de l'admin.",
        solutions="Cache avec invalidation par timestamp, slugs automatiques et balises meta, authentification par token.",
        perspectives="Système de commentaires, recherche full-text, support multi-langue, éditeur WYSIWYG.",
        lien_github="https://github.com/exemple/mini-cms",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 13 ──
    dict(
        libelle="Système de Gestion de Notes Étudiantes",
        type_projet="Académique",
        date_duree="Novembre 2025 – Janvier 2026",
        contexte="Projet de module Programmation Orientée Objet, L2 IR. Gestion des notes et moyennes pour un département universitaire.",
        problematique="Le calcul des moyennes, rattrapages et classements est fait manuellement sur Excel, source d'erreurs et de retards dans la publication des résultats.",
        objectif="Automatiser la saisie des notes, le calcul des moyennes pondérées, la gestion des rattrapages et la génération des relevés de notes.",
        description_detail="Application avec gestion des UE et modules, saisie des notes par les enseignants, calcul automatique des moyennes avec coefficients, gestion des sessions et rattrapages.",
        source_donnees="Base SQLite",
        type_donnees="Relationnelle (étudiants, UE, modules, notes, sessions)",
        taille_dataset="300 étudiants, 20 UE, 2 sessions",
        pretraitements="Import des listes étudiantes depuis CSV, validation des notes (0-20)",
        approche="POO avec héritage et polymorphisme",
        etapes="1. Modélisation des classes (Étudiant, UE, Module, Note)\n2. Logique de calcul des moyennes\n3. Interface de saisie\n4. Génération de relevés PDF\n5. Statistiques et classement\n6. Export Excel",
        algorithmes="Calcul de moyenne pondérée, règles de compensation entre UE, classement avec gestion des ex-aequo",
        langages="Python, SQL",
        librairies="Streamlit, Pandas, ReportLab, openpyxl, SQLite3",
        outils="VS Code, Git",
        frameworks="Streamlit",
        performances="Calcul des moyennes pour 300 étudiants en < 1s, génération PDF en < 3s",
        visualisations="Histogramme des notes par module, courbe de distribution, tableau de classement, taux de réussite par UE",
        resultats_concrets="Publication des résultats en 1 jour au lieu de 1 semaine, élimination des erreurs de calcul.",
        competences="POO avancée (héritage, polymorphisme), Manipulation de données, Génération PDF, Import/Export de fichiers",
        difficultes="Règles de compensation complexes entre UE, gestion des absences et notes éliminatoires, performance sur gros volumes.",
        solutions="Moteur de règles configurable, traitement par lots avec Pandas, cache des résultats calculés.",
        perspectives="Interface web complète, bulletin envoyé par email, analyse prédictive de réussite, API pour le portail étudiant.",
        lien_github="https://github.com/exemple/gestion-notes",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 14 ──
    dict(
        libelle="Générateur de Documentation Automatique",
        type_projet="Personnel",
        date_duree="Avril 2026",
        contexte="Projet personnel pour automatiser la génération de documentation technique à partir du code source Python.",
        problematique="La documentation technique est souvent absente ou obsolète car sa rédaction manuelle est fastidieuse et vite oubliée.",
        objectif="Créer un outil qui analyse le code Python (docstrings, signatures, structure) et génère automatiquement une documentation HTML/Markdown.",
        description_detail="Analyseur statique de code Python qui extrait les docstrings, les signatures de fonctions, les hiérarchies de classes et génère une documentation navigable.",
        source_donnees="Code source Python (fichiers .py)",
        type_donnees="Code source textuel",
        taille_dataset="Testé sur 15 projets Python (50-5000 lignes chacun)",
        pretraitements="Parsing AST (Abstract Syntax Tree), extraction des docstrings, analyse des imports",
        approche="Analyse statique de code avec le module ast de Python",
        etapes="1. Parsing AST des fichiers Python\n2. Extraction des métadonnées (classes, fonctions, docstrings)\n3. Moteur de templates pour le rendu\n4. Génération HTML et Markdown\n5. Navigation et recherche\n6. CLI pour l'intégration",
        algorithmes="Parcours d'arbre AST, résolution des imports relatifs, détection des design patterns",
        langages="Python, HTML, CSS, Markdown",
        librairies="ast (stdlib), Jinja2, Markdown2, Click",
        outils="VS Code, Git",
        frameworks="",
        performances="Analyse de 5000 lignes en < 2s, génération HTML en < 1s",
        visualisations="Documentation HTML navigable avec arborescence des modules, diagramme de classes simplifié",
        resultats_concrets="Documentation générée pour 5 projets personnels, gain de temps estimé à 4h par projet.",
        competences="Analyse statique de code, AST Python, Métaprogrammation, Génération de templates, CLI",
        difficultes="Gestion des décorateurs et métaclasses, docstrings dans différents formats (Google, NumPy, reStructuredText), imports circulaires.",
        solutions="Support multi-format de docstrings avec regex, gestion des imports circulaires par chargement lazy, fallback gracieux pour les cas complexes.",
        perspectives="Support de type hints (PEP 484), intégration GitHub Pages, analyse de couverture de documentation, support d'autres langages.",
        lien_github="https://github.com/exemple/auto-doc",
        lien_demo="", lien_rapport="", auteur="admin"
    ),

    # ── 15 ──
    dict(
        libelle="Plateforme d'Apprentissage en Ligne (Mini-LMS)",
        type_projet="Académique",
        date_duree="Février 2026 – Avril 2026",
        contexte="Projet de fin de semestre, L2 IR. Développement d'une plateforme e-learning simplifiée pour les cours de l'université.",
        problematique="Les enseignants n'ont pas de plateforme simple pour partager des cours, exercices et suivre la progression des étudiants.",
        objectif="Développer une plateforme LMS permettant de créer des cours structurés, d'assigner des exercices et de suivre la progression des étudiants.",
        description_detail="Plateforme avec espace enseignant (création de cours, chapitres, quiz) et espace étudiant (suivi de cours, soumission d'exercices, progression visuelle).",
        source_donnees="Base PostgreSQL",
        type_donnees="Relationnelle (cours, chapitres, quiz, soumissions, utilisateurs)",
        taille_dataset="20 cours, 100 chapitres, 50 quiz, 200 étudiants",
        pretraitements="Conversion des supports de cours existants (PDF, Word) en contenu web",
        approche="Application web multi-rôles (admin, enseignant, étudiant)",
        etapes="1. Analyse des besoins (interviews enseignants)\n2. Modélisation UML complète\n3. Développement backend et API\n4. Interface enseignant (CRUD cours)\n5. Interface étudiant (progression)\n6. Système de quiz avec correction automatique\n7. Tests et déploiement",
        algorithmes="Correction automatique de QCM, calcul de progression pondérée, algorithme de révision espacée (suggestion)",
        langages="Python, JavaScript, HTML, CSS, SQL",
        librairies="Flask, SQLAlchemy, Flask-Login, Chart.js, Markdown2",
        outils="VS Code, Git, GitHub, Figma, PostgreSQL",
        frameworks="Flask, Bootstrap 5",
        performances="Support de 200 étudiants simultanés, chargement des cours < 500ms",
        visualisations="Barre de progression par cours, graphique radar des compétences, tableau de bord enseignant avec taux de réussite",
        resultats_concrets="Plateforme testée par 2 enseignants et 40 étudiants pendant 3 semaines, taux de satisfaction de 85%.",
        competences="Architecture multi-rôles, Développement full-stack, UML complet, Gestion de projet, Tests utilisateurs, Design d'interface éducative",
        difficultes="Gestion des rôles et permissions complexes, correction automatique de réponses textuelles, performance avec beaucoup de données.",
        solutions="Système de permissions hiérarchique, correction par mots-clés et similarité pour le texte, lazy loading des contenus.",
        perspectives="Vidéo intégrée, forum de discussion par cours, certificats PDF automatiques, application mobile, gamification.",
        lien_github="https://github.com/exemple/mini-lms",
        lien_demo="", lien_rapport="", auteur="admin"
    ),
]
